# Generated by Django 5.2.4 on 2025-07-16 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0002_property_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this record was first created.",
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this record was last updated.",
                        verbose_name="Last Update Date & Time",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="The property that has been favorited by the user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_user",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who marked this property as a favorite.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Favorite Property",
                "verbose_name_plural": "User Favorite Properties",
                "ordering": ["-created_at"],
                "unique_together": {("user", "property")},
            },
        ),
    ]
