# Generated by Django 5.2.4 on 2025-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFavoriteProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this record was first created.",
                        verbose_name="Creation Date & Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this record was last updated.",
                        verbose_name="Last Update Date & Time",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Favorite Property",
                "verbose_name_plural": "User Favorite Properties",
                "ordering": ["-created_at"],
            },
        ),
    ]
