# Generated by Django 5.2.4 on 2025-07-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("favorites", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfavoriteproperty",
            name="property",
            field=models.ForeignKey(
                help_text="The property that has been favorited by the user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_user",
                to="properties.property",
            ),
        ),
    ]
