# Generated by Django 5.2.4 on 2025-07-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("favorites", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userfavoriteproperty",
            name="user",
            field=models.ForeignKey(
                help_text="The user who marked this property as a favorite.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfavoriteproperty",
            unique_together={("user", "property")},
        ),
    ]
