services:

  backend:
    image: balkan-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-api
    container_name: balkan-backend-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/homeapi/
      - /.mypy_cache
      - /.pytest_cache
      - /homeapi/.mypy_cache
      - /static
    depends_on:
      - postgres

  postgres:
    container_name: balkan-postgres
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
