# Generated by Django 5.2.4 on 2025-07-24 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user account associated with the creation or current ownership of this property listing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                help_text="Image belong to the given property.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_images",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "city"],
                name="properties__country_9f0bca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "property_type"],
                name="properties__country_6ef09e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "street_name"],
                name="properties__country_6396a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "price"],
                name="properties__country_c9a65a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "area"],
                name="properties__country_a2ae8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "postal_code"],
                name="properties__country_8d9516_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "total_rooms"],
                name="properties__country_e4e473_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "created_at"],
                name="properties__country_d11aec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "status", "construction_year"],
                name="properties__country_cd14c5_idx",
            ),
        ),
    ]
