# Generated by Django 4.2 on 2024-02-23 21:59

import apps.properties.models.property_image
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title  for the image.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for the image."
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image will be displayed first for the property.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the property.",
                        upload_to=apps.properties.models.property_image.property_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "bmp", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Image belong to the given property.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
    ]
