# Generated by Django 4.2 on 2024-03-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_status_genre_status_unique_model_status_name_and_more"),
        ("properties", "0002_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="Status of the property.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="status_properties",
                to="core.status",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type | Genre of the property.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="genre_properties",
                to="core.genre",
            ),
        ),
    ]
