# Generated by Django 5.2.4 on 2025-07-16 15:09

import apps.properties.models.property
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_created_at_alter_address_updated_at"),
        ("properties", "0002_property_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.ForeignKey(
                help_text="The physical address where the property is located.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="address_properties",
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.FloatField(
                help_text="The covered area of the property in square meters.\n            This refers to the total indoor living space, including all rooms,\n            hallways, and any other enclosed spaces within the structure.",
                validators=[apps.properties.models.property.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="construction_year",
            field=models.IntegerField(
                blank=True,
                help_text="The year in which the main construction of the property was completed.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    apps.properties.models.property.max_value_current_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this record was first created.",
                verbose_name="Creation Date & Time",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A comprehensive internal description highlighting the\n            key features, amenities, and unique selling points of the property\n            for administrative use.",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="heating",
            field=models.CharField(
                blank=True,
                help_text="Detailed description of the heating system, e.g.,\n            'Central heating with gas furnace' or 'Electric baseboard heating'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="measured_area",
            field=models.FloatField(
                blank=True,
                help_text="The officially measured and verified area of the property, typically used for legal or appraisal purposes.",
                null=True,
                validators=[apps.properties.models.property.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="outer_walls",
            field=models.CharField(
                blank=True,
                help_text="The primary material used for the exterior walls, e.g., 'Brick', 'Stucco', 'Wood siding'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user account associated with the creation or current ownership of this property listing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The asking price of the property.",
                max_digits=19,
                validators=[apps.properties.models.property.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price_currency",
            field=models.CharField(
                help_text="Provide the 3-letter currency code for the price (e.g., 'USD', 'EUR', 'GBP').",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="renovation_year",
            field=models.IntegerField(
                blank=True,
                help_text="The most recent year in which significant renovations or major updates were performed on the property.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    apps.properties.models.property.max_value_current_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="roof_type",
            field=models.CharField(
                blank=True,
                help_text="The type of roofing material and style, e.g., 'Tile', 'Shingle', 'Flat roof'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="The current transactional status of the property (e.g., 'For Sale', 'Under Contract', 'Sold', 'Rented').",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="status_properties",
                to="core.status",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="toilets",
            field=models.IntegerField(
                blank=True,
                help_text="The total number of toilet facilities in the property.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_area",
            field=models.FloatField(
                help_text="The total ground area of the property. This encompasses\n            the entire land area upon which the property is built, including\n            outdoor spaces such as yards, gardens, and driveways.",
                validators=[apps.properties.models.property.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(
                blank=True,
                help_text="The total number of floors or stories that the property comprises.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_rooms",
            field=models.FloatField(
                blank=True,
                help_text="The total number of distinct rooms within the property,\n            excluding bathrooms and kitchens unless specified otherwise.",
                null=True,
                validators=[apps.properties.models.property.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="The classification or genre of the property (e.g., 'Residential', 'Commercial', 'Apartment', 'House').",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="genre_properties",
                to="core.genre",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when this record was last updated.",
                verbose_name="Last Update Date & Time",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this record was first created.",
                verbose_name="Creation Date & Time",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when this record was last updated.",
                verbose_name="Last Update Date & Time",
            ),
        ),
    ]
