# Generated by Django 4.2 on 2024-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "street",
                    models.CharField(
                        help_text="Enter the street address", max_length=255
                    ),
                ),
                ("city", models.CharField(help_text="Enter the city", max_length=255)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Enter the region, state, or province (if applicable).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Enter the postal code or ZIP code.", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="Enter the country.", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
