# Generated by Django 5.2.4 on 2025-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this record was first created.",
                verbose_name="Creation Date & Time",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when this record was last updated.",
                verbose_name="Last Update Date & Time",
            ),
        ),
    ]
