# Generated by Django 4.2 on 2024-03-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Title or name of the status.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A short description of the type | genre. max 255 characters.",
                        max_length=255,
                    ),
                ),
                (
                    "sorting_order",
                    models.IntegerField(
                        default=1,
                        help_text="User defined sorting to control order in the dropdown. \n        Number for status among multiple status.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If set false then it should not appear in the status list.",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="The model on which this status will be used.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for the type | genre.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A short description of the type | genre. max 255 characters.",
                        max_length=255,
                    ),
                ),
                (
                    "sorting_order",
                    models.IntegerField(
                        blank=True,
                        help_text="To control order in the dropdown. This is the user defined sorting.",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to false to indicate that it will no longer be utilized.",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model on which this genre will be used.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                fields=("name", "model"), name="unique_model_status_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                fields=("name", "model"), name="unique_model_genre_name"
            ),
        ),
    ]
