# Generated by Django 4.2 on 2024-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_status_genre_status_unique_model_status_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="status",
            name="sorting_order",
            field=models.IntegerField(
                default=1,
                help_text="User defined sorting to control order in the dropdown.\n        Number for status among multiple status.",
            ),
        ),
    ]
