macedonia_cities = [
    {
        "name": "Berovo",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.71,
        "longitude": 22.85,
    },
    {
        "name": "Bitola",
        "slug": None,
        "region": "Пелагониски регион",  # Pelagonia Region
        "latitude": 41.03,
        "longitude": 21.33,
    },
    {
        "name": "Bogdanci",
        "slug": None,
        "region": "Југоисточен регион",  # Southeastern Region
        "latitude": 41.203056,
        "longitude": 22.575556,
    },
    {
        "name": "Češinovo-Obleševo",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.87,
        "longitude": 22.28,
    },
    {
        "name": "Debar",
        "slug": None,
        "region": "Југозападен регион",  # Southwestern Region
        "latitude": 41.5197573,
        "longitude": 20.5289,
    },
    {
        "name": "Delčevo",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.9667,
        "longitude": 22.7667,
    },
    {
        "name": "Demir Hisar",
        "slug": None,
        "region": "Пелагониски регион",  # Pelagonia Region
        "latitude": 41.220833,
        "longitude": 21.203056,
    },
    {
        "name": "Demir Kapija",
        "slug": None,
        "region": "Вардарски регион",  # Vardar Region
        "latitude": 41.4113,
        "longitude": 22.2422,
    },
    {
        "name": "Dojran",
        "slug": None,
        "region": "Југоисточен регион",  # Southeastern Region
        "latitude": 41.18,
        "longitude": 22.73,
    },
    {
        "name": "Gevgelija",
        "slug": None,
        "region": "Југоисточен регион",  # Southeastern Region
        "latitude": 41.14147,
        "longitude": 22.50460,
    },
    {
        "name": "Gostivar",
        "slug": None,
        "region": "Полошки регион",  # Polog Region
        "latitude": 41.800,
        "longitude": 20.917,
    },
    {
        "name": "Kavadarci",
        "slug": None,
        "region": "Вардарски регион",  # Vardar Region
        "latitude": 41.4333,
        "longitude": 22.0167,
    },
    {
        "name": "Kičevo",
        "slug": None,
        "region": "Југозападен регион",  # Southwestern Region
        "latitude": 41.517778,
        "longitude": 20.965556,
    },
    {
        "name": "Kočani",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.9167,
        "longitude": 22.4167,
    },
    {
        "name": "Kratovo",
        "slug": None,
        "region": "Североисточен регион",  # Northeastern Region
        "latitude": 42.0667,
        "longitude": 22.1833,
    },
    {
        "name": "Kriva Palanka",
        "slug": None,
        "region": "Североисточен регион",  # Northeastern Region
        "latitude": 42.2058454,
        "longitude": 22.3307965,
    },
    {
        "name": "Kruševo",
        "slug": None,
        "region": "Пелагониски регион",  # Pelagonia Region
        "latitude": 41.37,
        "longitude": 21.24,
    },
    {
        "name": "Kumanovo",
        "slug": None,
        "region": "Североисточен регион",  # Northeastern Region
        "latitude": 42.1358,
        "longitude": 21.7181,
    },
    {
        "name": "Makedonska Kamenica",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 42.019722,
        "longitude": 22.591667,
    },
    {
        "name": "Makedonski Brod",
        "slug": None,
        "region": "Југозападен регион",  # Southwestern Region
        "latitude": 41.50,
        "longitude": 21.21,
    },
    {
        "name": "Negotino",
        "slug": None,
        "region": "Вардарски регион",  # Vardar Region
        "latitude": 41.48,
        "longitude": 22.06,
    },
    {
        "name": "Ohrid",
        "slug": None,
        "region": "Југозападен регион",  # Southwestern Region
        "latitude": 41.117028,
        "longitude": 20.801703,
    },
    {
        "name": "Pehčevo",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.76,
        "longitude": 22.88,
    },
    {
        "name": "Prilep",
        "slug": None,
        "region": "Пелагониски регион",  # Pelagonia Region
        "latitude": 41.34,
        "longitude": 21.55,
    },
    {
        "name": "Probištip",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.99,
        "longitude": 22.18,
    },
    {
        "name": "Radoviš",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.63,
        "longitude": 22.46,
    },
    {
        "name": "Resen",
        "slug": None,
        "region": "Пелагониски регион",  # Pelagonia Region
        "latitude": 41.08,
        "longitude": 21.01,
    },
    {
        "name": "Skopje",
        "slug": None,
        "region": "Скопски регион",  # Skopje Region
        "latitude": 42.00,
        "longitude": 21.43,
    },
    {
        "name": "Struga",
        "slug": None,
        "region": "Југозападен регион",  # Southwestern Region
        "latitude": 41.17,
        "longitude": 20.67,
    },
    {
        "name": "Strumica",
        "slug": None,
        "region": "Југоисточен регион",  # Southeastern Region
        "latitude": 41.43,
        "longitude": 22.64,
    },
    {
        "name": "Sveti Nikole",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.86,
        "longitude": 21.94,
    },
    {
        "name": "Štip",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.74,
        "longitude": 22.19,
    },
    {
        "name": "Tetovo",
        "slug": None,
        "region": "Полошки регион",  # Polog Region
        "latitude": 42.01,
        "longitude": 20.97,
    },
    {
        "name": "Valandovo",
        "slug": None,
        "region": "Југоисточен регион",  # Southeastern Region
        "latitude": 41.20,
        "longitude": 22.56,
    },
    {
        "name": "Veles",
        "slug": None,
        "region": "Вардарски регион",  # Vardar Region
        "latitude": 41.71,
        "longitude": 21.77,
    },
    {
        "name": "Vinica",
        "slug": None,
        "region": "Источен регион",  # Eastern Region
        "latitude": 41.88,
        "longitude": 22.50,
    },
    {
        "name": "Aerodrom",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.98,
        "longitude": 21.45,
    },
    {
        "name": "Butel",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.03,
        "longitude": 21.45,
    },
    {
        "name": "Čair",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.01,
        "longitude": 21.44,
    },
    {
        "name": "Centar",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.00,
        "longitude": 21.43,
    },
    {
        "name": "Gazi Baba",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.02,
        "longitude": 21.45,
    },
    {
        "name": "Karpoš",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.00,
        "longitude": 21.39,
    },
    {
        "name": "Kisela Voda",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.95,
        "longitude": 21.50,
    },
    {
        "name": "Saraj",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.00,
        "longitude": 21.33,
    },
    {
        "name": "Šuto Orizari",  # Municipality within Skopje
        "slug": None,
        "region": "Скопски регион",
        "latitude": 42.04,
        "longitude": 21.42,
    },
    {
        "name": "Bogovinje",
        "slug": None,
        "region": "Полошки регион",
        "latitude": 41.92,
        "longitude": 20.92,
    },
    {
        "name": "Brvenica",
        "slug": None,
        "region": "Полошки регион",
        "latitude": 41.89,
        "longitude": 20.98,
    },
    {
        "name": "Čaška",
        "slug": None,
        "region": "Вардарски регион",
        "latitude": 41.65,
        "longitude": 21.66,
    },
    {
        "name": "Debarca",
        "slug": None,
        "region": "Југозападен регион",
        "latitude": 41.30,
        "longitude": 20.85,
    },
    {
        "name": "Dolneni",
        "slug": None,
        "region": "Пелагониски регион",
        "latitude": 41.43,
        "longitude": 21.45,
    },
    {
        "name": "Ilinden",
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.99,
        "longitude": 21.58,
    },
    {
        "name": "Jegunovce",
        "slug": None,
        "region": "Полошки регион",
        "latitude": 42.07,
        "longitude": 21.12,
    },
    {
        "name": "Karbinci",
        "slug": None,
        "region": "Источен регион",
        "latitude": 41.82,
        "longitude": 22.24,
    },
    {
        "name": "Konče",
        "slug": None,
        "region": "Источен регион",
        "latitude": 41.50,
        "longitude": 22.38,
    },
    {
        "name": "Lozovo",
        "slug": None,
        "region": "Вардарски регион",
        "latitude": 41.78,
        "longitude": 21.90,
    },
    {
        "name": "Mavrovo and Rostuša",
        "slug": None,
        "region": "Полошки регион",
        "latitude": 41.66,
        "longitude": 20.73,
    },
    {
        "name": "Novaci",
        "slug": None,
        "region": "Пелагониски регион",
        "latitude": 41.04,
        "longitude": 21.46,
    },
    {
        "name": "Novo Selo",
        "slug": None,
        "region": "Југоисточен регион",
        "latitude": 41.42,
        "longitude": 22.87,
    },
    {
        "name": "Petrovec",
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.94,
        "longitude": 21.62,
    },
    {
        "name": "Plasnica",
        "slug": None,
        "region": "Југозападен регион",
        "latitude": 41.47,
        "longitude": 21.12,
    },
    {
        "name": "Rankovce",
        "slug": None,
        "region": "Североисточен регион",
        "latitude": 42.18,
        "longitude": 22.12,
    },
    {
        "name": "Rosoman",
        "slug": None,
        "region": "Вардарски регион",
        "latitude": 41.52,
        "longitude": 21.95,
    },
    {
        "name": "Sopište",
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.95,
        "longitude": 21.41,
    },
    {
        "name": "Staro Nagoričane",
        "slug": None,
        "region": "Североисточен регион",
        "latitude": 42.20,
        "longitude": 21.83,
    },
    {
        "name": "Studeničani",
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.92,
        "longitude": 21.53,
    },
    {
        "name": "Tearce",
        "slug": None,
        "region": "Полошки регион",
        "latitude": 42.08,
        "longitude": 21.05,
    },
    {
        "name": "Vasilevo",
        "slug": None,
        "region": "Југоисточен регион",
        "latitude": 41.48,
        "longitude": 22.64,
    },
    {
        "name": "Vevčani",
        "slug": None,
        "region": "Југозападен регион",
        "latitude": 41.24,
        "longitude": 20.59,
    },
    {
        "name": "Zelenikovo",
        "slug": None,
        "region": "Скопски регион",
        "latitude": 41.89,
        "longitude": 21.59,
    },
    {
        "name": "Zrnovci",
        "slug": None,
        "region": "Источен регион",
        "latitude": 41.85,
        "longitude": 22.44,
    },
]

danish_cities = [
    {
        "name": "Aabenraa",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.031441,
        "longitude": 9.421235,
    },
    {
        "name": "Aalborg",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 57.03,
        "longitude": 9.55,
    },
    {
        "name": "Aarhus",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.15,
        "longitude": 10.22,
    },
    {
        "name": "Albertslund",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.659722,
        "longitude": 12.361667,
    },
    {
        "name": "Allerød",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.8719,
        "longitude": 12.3422,
    },
    {
        "name": "Assens",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.2667,
        "longitude": 9.8833,
    },
    {
        "name": "Ballerup",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.7316,
        "longitude": 12.3633,
    },
    {
        "name": "Billund",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.73,
        "longitude": 9.11,
    },
    {
        "name": "Bornholm",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.15,
        "longitude": 14.9167,
    },
    {
        "name": "Brøndby",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6473055,
        "longitude": 12.414886,
    },
    {
        "name": "Brønderslev",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 57.2694,
        "longitude": 9.9472,
    },
    {
        "name": "Copenhagen",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.68,
        "longitude": 12.59,
    },
    {
        "name": "Dragør",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.583328,
        "longitude": 12.666670,
    },
    {
        "name": "Egedal",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.768611,
        "longitude": 12.212778,
    },
    {
        "name": "Esbjerg",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.4703,
        "longitude": 8.4519,
    },
    {
        "name": "Faaborg-Midtfyn",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.1667,
        "longitude": 10.3333,
    },
    {
        "name": "Faxe",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.255278,
        "longitude": 12.119722,
    },
    {
        "name": "Favrskov",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.328611,
        "longitude": 10.046111,
    },
    {
        "name": "Fredensborg",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.975,
        "longitude": 12.405556,
    },
    {
        "name": "Fredericia",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.5833,
        "longitude": 9.75,
    },
    {
        "name": "Frederikshavn",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 57.4333,
        "longitude": 10.5333,
    },
    {
        "name": "Frederikssund",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.85,
        "longitude": 12.05,
    },
    {
        "name": "Furesø",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.77,
        "longitude": 12.36,
    },
    {
        "name": "Gentofte",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.7333,
        "longitude": 12.5667,
    },
    {
        "name": "Gladsaxe",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.7333,
        "longitude": 12.4667,
    },
    {
        "name": "Glostrup",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6667,
        "longitude": 12.3833,
    },
    {
        "name": "Greve",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.5833,
        "longitude": 12.2167,
    },
    {
        "name": "Grenaa",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.4167,
        "longitude": 10.8833,
    },
    {
        "name": "Gribskov",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 56.0833,
        "longitude": 12.2833,
    },
    {
        "name": "Guldborgsund",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 54.7667,
        "longitude": 11.8833,
    },
    {
        "name": "Haderslev",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.25,
        "longitude": 9.4833,
    },
    {
        "name": "Halsnæs",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.95,
        "longitude": 12.05,
    },
    {
        "name": "Hedensted",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 55.7833,
        "longitude": 9.8833,
    },
    {
        "name": "Helsingør",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 56.0333,
        "longitude": 12.6167,
    },
    {
        "name": "Herlev",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.7167,
        "longitude": 12.4333,
    },
    {
        "name": "Herning",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.1333,
        "longitude": 8.9667,
    },
    {
        "name": "Hillerød",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.9333,
        "longitude": 12.30,
    },
    {
        "name": "Hjørring",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 57.4667,
        "longitude": 10.0167,
    },
    {
        "name": "Holbæk",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.7167,
        "longitude": 11.7167,
    },
    {
        "name": "Holstebro",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.3667,
        "longitude": 8.6167,
    },
    {
        "name": "Horsens",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 55.8667,
        "longitude": 9.8333,
    },
    {
        "name": "Hvidovre",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6333,
        "longitude": 12.4667,
    },
    {
        "name": "Høje-Taastrup",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.65,
        "longitude": 12.2833,
    },
    {
        "name": "Hørsholm",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.95,
        "longitude": 12.50,
    },
    {
        "name": "Ikast-Brande",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.1333,
        "longitude": 9.15,
    },
    {
        "name": "Ishøj",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.60,
        "longitude": 12.35,
    },
    {
        "name": "Kalundborg",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.6833,
        "longitude": 11.0833,
    },
    {
        "name": "Kerteminde",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.45,
        "longitude": 10.65,
    },
    {
        "name": "Kolding",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.4833,
        "longitude": 9.4667,
    },
    {
        "name": "Køge",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.45,
        "longitude": 12.1833,
    },
    {
        "name": "Langeland",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 54.9167,
        "longitude": 10.75,
    },
    {
        "name": "Lejre",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.60,
        "longitude": 11.9667,
    },
    {
        "name": "Lemvig",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.55,
        "longitude": 8.30,
    },
    {
        "name": "Lolland",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 54.7667,
        "longitude": 11.3333,
    },
    {
        "name": "Lyngby-Taarbæk",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.7667,
        "longitude": 12.5833,
    },
    {
        "name": "Mariagerfjord",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 56.70,
        "longitude": 10.00,
    },
    {
        "name": "Middelfart",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.50,
        "longitude": 9.7333,
    },
    {
        "name": "Morsø",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 56.80,
        "longitude": 8.7833,
    },
    {
        "name": "Næstved",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.2333,
        "longitude": 11.7667,
    },
    {
        "name": "Norddjurs",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.4667,
        "longitude": 10.6667,
    },
    {
        "name": "Nordfyns",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.55,
        "longitude": 10.2667,
    },
    {
        "name": "Nyborg",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.3167,
        "longitude": 10.7833,
    },
    {
        "name": "Nykøbing Falster",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 54.7667,
        "longitude": 11.8833,
    },
    {
        "name": "Odder",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 55.9667,
        "longitude": 10.15,
    },
    {
        "name": "Odense",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.40,
        "longitude": 10.3833,
    },
    {
        "name": "Odsherred",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.8833,
        "longitude": 11.45,
    },
    {
        "name": "Randers",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.4667,
        "longitude": 10.0333,
    },
    {
        "name": "Rebild",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 56.8667,
        "longitude": 9.8333,
    },
    {
        "name": "Ringkøbing-Skjern",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.00,
        "longitude": 8.2833,
    },
    {
        "name": "Ringsted",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.45,
        "longitude": 11.7833,
    },
    {
        "name": "Roskilde",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.65,
        "longitude": 12.0833,
    },
    {
        "name": "Rudersdal",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.80,
        "longitude": 12.4667,
    },
    {
        "name": "Rødovre",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6833,
        "longitude": 12.45,
    },
    {
        "name": "Samsø",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 55.8833,
        "longitude": 10.60,
    },
    {
        "name": "Silkeborg",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.1667,
        "longitude": 9.55,
    },
    {
        "name": "Skanderborg",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.0333,
        "longitude": 9.9333,
    },
    {
        "name": "Skive",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.5667,
        "longitude": 9.0333,
    },
    {
        "name": "Slagelse",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.4167,
        "longitude": 11.35,
    },
    {
        "name": "Solrød",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.5333,
        "longitude": 12.1833,
    },
    {
        "name": "Sorø",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.45,
        "longitude": 11.5667,
    },
    {
        "name": "Struer",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.4833,
        "longitude": 8.5833,
    },
    {
        "name": "Svendborg",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.05,
        "longitude": 10.60,
    },
    {
        "name": "Sønderborg",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 54.9167,
        "longitude": 9.7833,
    },
    {
        "name": "Syddjurs",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.2667,
        "longitude": 10.4667,
    },
    {
        "name": "Tårnby",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6167,
        "longitude": 12.60,
    },
    {
        "name": "Thisted",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 56.8833,
        "longitude": 8.6833,
    },
    {
        "name": "Tønder",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 54.9333,
        "longitude": 8.8667,
    },
    {
        "name": "Vallensbæk",
        "slug": None,
        "region": "Region Hovedstaden",
        "latitude": 55.6333,
        "longitude": 12.3833,
    },
    {
        "name": "Varde",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.60,
        "longitude": 8.4833,
    },
    {
        "name": "Vejle",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 55.7167,
        "longitude": 9.5333,
    },
    {
        "name": "Vesthimmerlands",
        "slug": None,
        "region": "Region Nordjylland",
        "latitude": 56.80,
        "longitude": 9.50,
    },
    {
        "name": "Viborg",
        "slug": None,
        "region": "Region Midtjylland",
        "latitude": 56.45,
        "longitude": 9.40,
    },
    {
        "name": "Vordingborg",
        "slug": None,
        "region": "Region Sjælland",
        "latitude": 55.00,
        "longitude": 11.90,
    },
    {
        "name": "Ærø",
        "slug": None,
        "region": "Region Syddanmark",
        "latitude": 54.90,
        "longitude": 10.30,
    },
]
