import unicodedata


def slugify(text: str) -> str:
    """
    Generates a slug from a given text.
    Converts to lowercase, removes/replaces non-ASCII characters,
    and replaces spaces with hyphens.
    """
    text = str(text)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = text.lower()
    text = text.replace(" ", "-")
    text = "".join(char for char in text if char.isalnum() or char == "-")
    text = text.strip("-")
    return text


macedonia_cities = [
    {
        "name": "Berovo",
        "slug": slugify("Berovo"),
        "region": None,
        "latitude": 41.71,
        "longitude": 22.85,
    },
    {
        "name": "Bitola",
        "slug": slugify("Bitola"),
        "region": None,
        "latitude": 41.03,
        "longitude": 21.33,
    },
    {
        "name": "Bogdanci",
        "slug": slugify("Bogdanci"),
        "region": None,
        "latitude": 41.203056,
        "longitude": 22.575556,
    },
    {
        "name": "Debar",
        "slug": slugify("Debar"),
        "region": None,
        "latitude": 41.5197573,
        "longitude": 20.5289,
    },
    {
        "name": "Delčevo",
        "slug": slugify("Delcevo"),
        "region": None,
        "latitude": 41.9667,
        "longitude": 22.7667,
    },
    {
        "name": "Demir Hisar",
        "slug": slugify("Demir Hisar"),
        "region": None,
        "latitude": 41.220833,
        "longitude": 21.203056,
    },
    {
        "name": "Demir Kapija",
        "slug": slugify("Demir Kapija"),
        "region": None,
        "latitude": 41.4113,
        "longitude": 22.2422,
    },
    {
        "name": "Gevgelija",
        "slug": slugify("Gevgelija"),
        "region": None,
        "latitude": 41.14147,
        "longitude": 22.50460,
    },
    {
        "name": "Gostivar",
        "slug": slugify("Gostivar"),
        "region": None,
        "latitude": 41.800,
        "longitude": 20.917,
    },
    {
        "name": "Kavadarci",
        "slug": slugify("Kavadarci"),
        "region": None,
        "latitude": 41.4333,
        "longitude": 22.0167,
    },
    {
        "name": "Kičevo",
        "slug": slugify("Kicevo"),
        "region": None,
        "latitude": 41.517778,
        "longitude": 20.965556,
    },
    {
        "name": "Kočani",
        "slug": slugify("Kocani"),
        "region": None,
        "latitude": 41.9167,
        "longitude": 22.4167,
    },
    {
        "name": "Kratovo",
        "slug": slugify("Kratovo"),
        "region": None,
        "latitude": 42.0667,
        "longitude": 22.1833,
    },
    {
        "name": "Kriva Palanka",
        "slug": slugify("Kriva Palanka"),
        "region": None,
        "latitude": 42.2058454,
        "longitude": 22.3307965,
    },
    {
        "name": "Kruševo",
        "slug": slugify("Krusevo"),
        "region": None,
        "latitude": 41.37,
        "longitude": 21.24,
    },
    {
        "name": "Kumanovo",
        "slug": slugify("Kumanovo"),
        "region": None,
        "latitude": 42.1358,
        "longitude": 21.7181,
    },
    {
        "name": "Makedonska Kamenica",
        "slug": slugify("Makedonska Kamenica"),
        "region": None,
        "latitude": 42.019722,
        "longitude": 22.591667,
    },
    {
        "name": "Makedonski Brod",
        "slug": slugify("Makedonski Brod"),
        "region": None,
        "latitude": 41.50,
        "longitude": 21.21,
    },
    {
        "name": "Negotino",
        "slug": slugify("Negotino"),
        "region": None,
        "latitude": 41.48,
        "longitude": 22.06,
    },
    {
        "name": "Ohrid",
        "slug": slugify("Ohrid"),
        "region": None,
        "latitude": 41.117028,
        "longitude": 20.801703,
    },
    {
        "name": "Pehčevo",
        "slug": slugify("Pehcevo"),
        "region": None,
        "latitude": 41.76,
        "longitude": 22.88,
    },
    {
        "name": "Prilep",
        "slug": slugify("Prilep"),
        "region": None,
        "latitude": 41.34,
        "longitude": 21.55,
    },
    {
        "name": "Probištip",
        "slug": slugify("Probistip"),
        "region": None,
        "latitude": 41.99,
        "longitude": 22.18,
    },
    {
        "name": "Radoviš",
        "slug": slugify("Radovis"),
        "region": None,
        "latitude": 41.63,
        "longitude": 22.46,
    },
    {
        "name": "Resen",
        "slug": slugify("Resen"),
        "region": None,
        "latitude": 41.08,
        "longitude": 21.01,
    },
    {
        "name": "Skopje",
        "slug": slugify("Skopje"),
        "region": None,
        "latitude": 42.00,
        "longitude": 21.43,
    },
    {
        "name": "Struga",
        "slug": slugify("Struga"),
        "region": None,
        "latitude": 41.17,
        "longitude": 20.67,
    },
    {
        "name": "Strumica",
        "slug": slugify("Strumica"),
        "region": None,
        "latitude": 41.43,
        "longitude": 22.64,
    },
    {
        "name": "Sveti Nikole",
        "slug": slugify("Sveti Nikole"),
        "region": None,
        "latitude": 41.86,
        "longitude": 21.94,
    },
    {
        "name": "Štip",
        "slug": slugify("Stip"),
        "region": None,
        "latitude": 41.74,
        "longitude": 22.19,
    },
    {
        "name": "Tetovo",
        "slug": slugify("Tetovo"),
        "region": None,
        "latitude": 42.01,
        "longitude": 20.97,
    },
    {
        "name": "Valandovo",
        "slug": slugify("Valandovo"),
        "region": None,
        "latitude": 41.20,
        "longitude": 22.56,
    },
    {
        "name": "Veles",
        "slug": slugify("Veles"),
        "region": None,
        "latitude": 41.71,
        "longitude": 21.77,
    },
    {
        "name": "Vinica",
        "slug": slugify("Vinica"),
        "region": None,
        "latitude": 41.88,
        "longitude": 22.50,
    },
]

danish_cities = [
    {
        "name": "Aabenraa",
        "slug": slugify("Aabenraa"),
        "region": None,
        "latitude": 55.031441,
        "longitude": 9.421235,
    },
    {
        "name": "Aalborg",
        "slug": slugify("Aalborg"),
        "region": None,
        "latitude": 57.03,
        "longitude": 9.55,
    },
    {
        "name": "Aarhus",
        "slug": slugify("Aarhus"),
        "region": None,
        "latitude": 56.15,
        "longitude": 10.22,
    },
    {
        "name": "Albertslund",
        "slug": slugify("Albertslund"),
        "region": None,
        "latitude": 55.659722,
        "longitude": 12.361667,
    },
    {
        "name": "Allerød",
        "slug": slugify("Allerod"),
        "region": None,
        "latitude": 55.8719,
        "longitude": 12.3422,
    },
    {
        "name": "Assens",
        "slug": slugify("Assens"),
        "region": None,
        "latitude": 55.2667,
        "longitude": 9.8833,
    },
    {
        "name": "Ballerup",
        "slug": slugify("Ballerup"),
        "region": None,
        "latitude": 55.7316,
        "longitude": 12.3633,
    },
    {
        "name": "Billund",
        "slug": slugify("Billund"),
        "region": None,
        "latitude": 55.73,
        "longitude": 9.11,
    },
    {
        "name": "Bornholm",
        "slug": slugify("Bornholm"),
        "region": None,
        "latitude": 55.15,
        "longitude": 14.9167,
    },
    {
        "name": "Brøndby",
        "slug": slugify("Brondby"),
        "region": None,
        "latitude": 55.6473055,
        "longitude": 12.414886,
    },
    {
        "name": "Brønderslev",
        "slug": slugify("Bronderslev"),
        "region": None,
        "latitude": 57.2694,
        "longitude": 9.9472,
    },
    {
        "name": "Copenhagen",
        "slug": slugify("Copenhagen"),
        "region": None,
        "latitude": 55.68,
        "longitude": 12.59,
    },
    {
        "name": "Dragør",
        "slug": slugify("Dragor"),
        "region": None,
        "latitude": 55.583328,
        "longitude": 12.666670,
    },
    {
        "name": "Egedal",
        "slug": slugify("Egedal"),
        "region": None,
        "latitude": 55.768611,
        "longitude": 12.212778,
    },
    {
        "name": "Esbjerg",
        "slug": slugify("Esbjerg"),
        "region": None,
        "latitude": 55.4703,
        "longitude": 8.4519,
    },
    {
        "name": "Faaborg-Midtfyn",
        "slug": slugify("Faaborg-Midtfyn"),
        "region": None,
        "latitude": 55.1667,
        "longitude": 10.3333,
    },
    {
        "name": "Faxe",
        "slug": slugify("Faxe"),
        "region": None,
        "latitude": 55.255278,
        "longitude": 12.119722,
    },
    {
        "name": "Favrskov",
        "slug": slugify("Favrskov"),
        "region": None,
        "latitude": 56.328611,
        "longitude": 10.046111,
    },
    {
        "name": "Fredensborg",
        "slug": slugify("Fredensborg"),
        "region": None,
        "latitude": 55.975,
        "longitude": 12.405556,
    },
    {
        "name": "Fredericia",
        "slug": slugify("Fredericia"),
        "region": None,
        "latitude": 55.5833,
        "longitude": 9.75,
    },
    {
        "name": "Frederikshavn",
        "slug": slugify("Frederikshavn"),
        "region": None,
        "latitude": 57.4333,
        "longitude": 10.5333,
    },
    {
        "name": "Frederikssund",
        "slug": slugify("Frederikssund"),
        "region": None,
        "latitude": 55.85,
        "longitude": 12.05,
    },
    {
        "name": "Furesø",
        "slug": slugify("Fureso"),
        "region": None,
        "latitude": 55.77,
        "longitude": 12.36,
    },
    {
        "name": "Gentofte",
        "slug": slugify("Gentofte"),
        "region": None,
        "latitude": 55.7333,
        "longitude": 12.5667,
    },
    {
        "name": "Gladsaxe",
        "slug": slugify("Gladsaxe"),
        "region": None,
        "latitude": 55.7333,
        "longitude": 12.4667,
    },
    {
        "name": "Glostrup",
        "slug": slugify("Glostrup"),
        "region": None,
        "latitude": 55.6667,
        "longitude": 12.3833,
    },
    {
        "name": "Greve",
        "slug": slugify("Greve"),
        "region": None,
        "latitude": 55.5833,
        "longitude": 12.2167,
    },
    {
        "name": "Grenaa",
        "slug": slugify("Grenaa"),
        "region": None,
        "latitude": 56.4167,
        "longitude": 10.8833,
    },
    {
        "name": "Gribskov",
        "slug": slugify("Gribskov"),
        "region": None,
        "latitude": 56.0833,
        "longitude": 12.2833,
    },
    {
        "name": "Guldborgsund",
        "slug": slugify("Guldborgsund"),
        "region": None,
        "latitude": 54.7667,
        "longitude": 11.8833,
    },
    {
        "name": "Haderslev",
        "slug": slugify("Haderslev"),
        "region": None,
        "latitude": 55.25,
        "longitude": 9.4833,
    },
    {
        "name": "Halsnæs",
        "slug": slugify("Halsnaes"),
        "region": None,
        "latitude": 55.95,
        "longitude": 12.05,
    },
    {
        "name": "Hedensted",
        "slug": slugify("Hedensted"),
        "region": None,
        "latitude": 55.7833,
        "longitude": 9.8833,
    },
    {
        "name": "Helsingør",
        "slug": slugify("Helsingor"),
        "region": None,
        "latitude": 56.0333,
        "longitude": 12.6167,
    },
    {
        "name": "Herlev",
        "slug": slugify("Herlev"),
        "region": None,
        "latitude": 55.7167,
        "longitude": 12.4333,
    },
    {
        "name": "Herning",
        "slug": slugify("Herning"),
        "region": None,
        "latitude": 56.1333,
        "longitude": 8.9667,
    },
    {
        "name": "Hillerød",
        "slug": slugify("Hillerod"),
        "region": None,
        "latitude": 55.9333,
        "longitude": 12.30,
    },
    {
        "name": "Hjørring",
        "slug": slugify("Hjorring"),
        "region": None,
        "latitude": 57.4667,
        "longitude": 10.0167,
    },
    {
        "name": "Holbæk",
        "slug": slugify("Holbaek"),
        "region": None,
        "latitude": 55.7167,
        "longitude": 11.7167,
    },
    {
        "name": "Holstebro",
        "slug": slugify("Holstebro"),
        "region": None,
        "latitude": 56.3667,
        "longitude": 8.6167,
    },
    {
        "name": "Horsens",
        "slug": slugify("Horsens"),
        "region": None,
        "latitude": 55.8667,
        "longitude": 9.8333,
    },
    {
        "name": "Hvidovre",
        "slug": slugify("Hvidovre"),
        "region": None,
        "latitude": 55.6333,
        "longitude": 12.4667,
    },
    {
        "name": "Høje-Taastrup",
        "slug": slugify("Hoje-Taastrup"),
        "region": None,
        "latitude": 55.65,
        "longitude": 12.2833,
    },
    {
        "name": "Hørsholm",
        "slug": slugify("Horsholm"),
        "region": None,
        "latitude": 55.95,
        "longitude": 12.50,
    },
    {
        "name": "Ikast-Brande",
        "slug": slugify("Ikast-Brande"),
        "region": None,
        "latitude": 56.1333,
        "longitude": 9.15,
    },
    {
        "name": "Ishøj",
        "slug": slugify("Ishoj"),
        "region": None,
        "latitude": 55.60,
        "longitude": 12.35,
    },
    {
        "name": "Kalundborg",
        "slug": slugify("Kalundborg"),
        "region": None,
        "latitude": 55.6833,
        "longitude": 11.0833,
    },
    {
        "name": "Kerteminde",
        "slug": slugify("Kerteminde"),
        "region": None,
        "latitude": 55.45,
        "longitude": 10.65,
    },
    {
        "name": "Kolding",
        "slug": slugify("Kolding"),
        "region": None,
        "latitude": 55.4833,
        "longitude": 9.4667,
    },
    {
        "name": "Køge",
        "slug": slugify("Koge"),
        "region": None,
        "latitude": 55.45,
        "longitude": 12.1833,
    },
    {
        "name": "Langeland",
        "slug": slugify("Langeland"),
        "region": None,
        "latitude": 54.9167,
        "longitude": 10.75,
    },
    {
        "name": "Lejre",
        "slug": slugify("Lejre"),
        "region": None,
        "latitude": 55.60,
        "longitude": 11.9667,
    },
    {
        "name": "Lemvig",
        "slug": slugify("Lemvig"),
        "region": None,
        "latitude": 56.55,
        "longitude": 8.30,
    },
    {
        "name": "Lolland",
        "slug": slugify("Lolland"),
        "region": None,
        "latitude": 54.7667,
        "longitude": 11.3333,
    },
    {
        "name": "Lyngby-Taarbæk",
        "slug": slugify("Lyngby-Taarbaek"),
        "region": None,
        "latitude": 55.7667,
        "longitude": 12.5833,
    },
    {
        "name": "Mariagerfjord",
        "slug": slugify("Mariagerfjord"),
        "region": None,
        "latitude": 56.70,
        "longitude": 10.00,
    },
    {
        "name": "Middelfart",
        "slug": slugify("Middelfart"),
        "region": None,
        "latitude": 55.50,
        "longitude": 9.7333,
    },
    {
        "name": "Morsø",
        "slug": slugify("Morso"),
        "region": None,
        "latitude": 56.80,
        "longitude": 8.7833,
    },
    {
        "name": "Næstved",
        "slug": slugify("Naestved"),
        "region": None,
        "latitude": 55.2333,
        "longitude": 11.7667,
    },
    {
        "name": "Norddjurs",
        "slug": slugify("Norddjurs"),
        "region": None,
        "latitude": 56.4667,
        "longitude": 10.6667,
    },
    {
        "name": "Nordfyns",
        "slug": slugify("Nordfyns"),
        "region": None,
        "latitude": 55.55,
        "longitude": 10.2667,
    },
    {
        "name": "Nyborg",
        "slug": slugify("Nyborg"),
        "region": None,
        "latitude": 55.3167,
        "longitude": 10.7833,
    },
    {
        "name": "Nykøbing Falster",
        "slug": slugify("Nykobing Falster"),
        "region": None,
        "latitude": 54.7667,
        "longitude": 11.8833,
    },
    {
        "name": "Odder",
        "slug": slugify("Odder"),
        "region": None,
        "latitude": 55.9667,
        "longitude": 10.15,
    },
    {
        "name": "Odense",
        "slug": slugify("Odense"),
        "region": None,
        "latitude": 55.40,
        "longitude": 10.3833,
    },
    {
        "name": "Odsherred",
        "slug": slugify("Odsherred"),
        "region": None,
        "latitude": 55.8833,
        "longitude": 11.45,
    },
    {
        "name": "Randers",
        "slug": slugify("Randers"),
        "region": None,
        "latitude": 56.4667,
        "longitude": 10.0333,
    },
    {
        "name": "Rebild",
        "slug": slugify("Rebild"),
        "region": None,
        "latitude": 56.8667,
        "longitude": 9.8333,
    },
    {
        "name": "Ringkøbing-Skjern",
        "slug": slugify("Ringkobing-Skjern"),
        "region": None,
        "latitude": 56.00,
        "longitude": 8.2833,
    },
    {
        "name": "Ringsted",
        "slug": slugify("Ringsted"),
        "region": None,
        "latitude": 55.45,
        "longitude": 11.7833,
    },
    {
        "name": "Roskilde",
        "slug": slugify("Roskilde"),
        "region": None,
        "latitude": 55.65,
        "longitude": 12.0833,
    },
    {
        "name": "Rudersdal",
        "slug": slugify("Rudersdal"),
        "region": None,
        "latitude": 55.80,
        "longitude": 12.4667,
    },
    {
        "name": "Rødovre",
        "slug": slugify("Rodovre"),
        "region": None,
        "latitude": 55.6833,
        "longitude": 12.45,
    },
    {
        "name": "Samsø",
        "slug": slugify("Samso"),
        "region": None,
        "latitude": 55.8833,
        "longitude": 10.60,
    },
    {
        "name": "Silkeborg",
        "slug": slugify("Silkeborg"),
        "region": None,
        "latitude": 56.1667,
        "longitude": 9.55,
    },
    {
        "name": "Skanderborg",
        "slug": slugify("Skanderborg"),
        "region": None,
        "latitude": 56.0333,
        "longitude": 9.9333,
    },
    {
        "name": "Skive",
        "slug": slugify("Skive"),
        "region": None,
        "latitude": 56.5667,
        "longitude": 9.0333,
    },
    {
        "name": "Slagelse",
        "slug": slugify("Slagelse"),
        "region": None,
        "latitude": 55.4167,
        "longitude": 11.35,
    },
    {
        "name": "Solrød",
        "slug": slugify("Solrod"),
        "region": None,
        "latitude": 55.5333,
        "longitude": 12.1833,
    },
    {
        "name": "Sorø",
        "slug": slugify("Soro"),
        "region": None,
        "latitude": 55.45,
        "longitude": 11.5667,
    },
    {
        "name": "Struer",
        "slug": slugify("Struer"),
        "region": None,
        "latitude": 56.4833,
        "longitude": 8.5833,
    },
    {
        "name": "Svendborg",
        "slug": slugify("Svendborg"),
        "region": None,
        "latitude": 55.05,
        "longitude": 10.60,
    },
    {
        "name": "Sønderborg",
        "slug": slugify("Sonderborg"),
        "region": None,
        "latitude": 54.9167,
        "longitude": 9.7833,
    },
    {
        "name": "Syddjurs",
        "slug": slugify("Syddjurs"),
        "region": None,
        "latitude": 56.2667,
        "longitude": 10.4667,
    },
    {
        "name": "Tårnby",
        "slug": slugify("Tarnby"),
        "region": None,
        "latitude": 55.6167,
        "longitude": 12.60,
    },
    {
        "name": "Thisted",
        "slug": slugify("Thisted"),
        "region": None,
        "latitude": 56.8833,
        "longitude": 8.6833,
    },
    {
        "name": "Tønder",
        "slug": slugify("Tonder"),
        "region": None,
        "latitude": 54.9333,
        "longitude": 8.8667,
    },
    {
        "name": "Vallensbæk",
        "slug": slugify("Vallensbaek"),
        "region": None,
        "latitude": 55.6333,
        "longitude": 12.3833,
    },
    {
        "name": "Varde",
        "slug": slugify("Varde"),
        "region": None,
        "latitude": 55.60,
        "longitude": 8.4833,
    },
    {
        "name": "Vejle",
        "slug": slugify("Vejle"),
        "region": None,
        "latitude": 55.7167,
        "longitude": 9.5333,
    },
    {
        "name": "Vesthimmerlands",
        "slug": slugify("Vesthimmerlands"),
        "region": None,
        "latitude": 56.80,
        "longitude": 9.50,
    },
    {
        "name": "Viborg",
        "slug": slugify("Viborg"),
        "region": None,
        "latitude": 56.45,
        "longitude": 9.40,
    },
    {
        "name": "Vordingborg",
        "slug": slugify("Vordingborg"),
        "region": None,
        "latitude": 55.00,
        "longitude": 11.90,
    },
    {
        "name": "Ærø",
        "slug": slugify("Aero"),
        "region": None,
        "latitude": 54.90,
        "longitude": 10.30,
    },
]
