countries_data = [
    {"name": "Albania", "code": "AL", "native_name": "Shqipëria"},
    {"name": "Andorra", "code": "AD", "native_name": "Andorra"},
    {"name": "Australia", "code": "AU", "native_name": "Australia"},
    {"name": "Austria", "code": "AT", "native_name": "Österreich"},
    {"name": "Bangladesh", "code": "BD", "native_name": "বাংলাদেশ"},
    {"name": "Belarus", "code": "BY", "native_name": "Беларусь"},
    {"name": "Belgium", "code": "BE", "native_name": "België"},
    {
        "name": "Bosnia and Herzegovina",
        "code": "BA",
        "native_name": "Bosna i Hercegovina",
    },
    {"name": "Brazil", "code": "BR", "native_name": "Brasil"},
    {"name": "Bulgaria", "code": "BG", "native_name": "България"},
    {"name": "Canada", "code": "CA", "native_name": "Canada"},
    {"name": "China", "code": "CN", "native_name": "中国"},
    {"name": "Croatia", "code": "HR", "native_name": "Hrvatska"},
    {"name": "Cyprus", "code": "CY", "native_name": "Κύπρος"},
    {"name": "Czechia", "code": "CZ", "native_name": "Česko"},
    {"name": "Denmark", "code": "DK", "native_name": "Danmark"},
    {"name": "Estonia", "code": "EE", "native_name": "Eesti"},
    {"name": "Finland", "code": "FI", "native_name": "Suomi"},
    {"name": "France", "code": "FR", "native_name": "France"},
    {"name": "Germany", "code": "DE", "native_name": "Deutschland"},
    {"name": "Greece", "code": "GR", "native_name": "Ελλάδα"},
    {"name": "Hungary", "code": "HU", "native_name": "Magyarország"},
    {"name": "Iceland", "code": "IS", "native_name": "Ísland"},
    {"name": "India", "code": "IN", "native_name": "भारत"},
    {"name": "Ireland", "code": "IE", "native_name": "Éire"},
    {"name": "Italy", "code": "IT", "native_name": "Italia"},
    {"name": "Japan", "code": "JP", "native_name": "日本"},
    {"name": "Kosovo", "code": "XK", "native_name": "Kosova"},
    {"name": "Latvia", "code": "LV", "native_name": "Latvija"},
    {"name": "Liechtenstein", "code": "LI", "native_name": "Liechtenstein"},
    {"name": "Lithuania", "code": "LT", "native_name": "Lietuva"},
    {"name": "Luxembourg", "code": "LU", "native_name": "Lëtzebuerg"},
    {"name": "Malta", "code": "MT", "native_name": "Malta"},
    {"name": "Moldova", "code": "MD", "native_name": "Republica Moldova"},
    {"name": "Monaco", "code": "MC", "native_name": "Monaco"},
    {"name": "Montenegro", "code": "ME", "native_name": "Crna Gora"},
    {"name": "Netherlands", "code": "NL", "native_name": "Nederland"},
    {"name": "New Zealand", "code": "NZ", "native_name": "New Zealand"},
    {"name": "North Macedonia", "code": "MK", "native_name": "Северна Македонија"},
    {"name": "Norway", "code": "NO", "native_name": "Norge"},
    {"name": "Pakistan", "code": "PK", "native_name": "پاکستان"},
    {"name": "Poland", "code": "PL", "native_name": "Polska"},
    {"name": "Portugal", "code": "PT", "native_name": "Portugal"},
    {"name": "Qatar", "code": "QA", "native_name": "قطر"},
    {"name": "Romania", "code": "RO", "native_name": "România"},
    {"name": "San Marino", "code": "SM", "native_name": "San Marino"},
    {"name": "Saudi Arabia", "code": "SA", "native_name": "المملكة العربية السعودية"},
    {"name": "Serbia", "code": "RS", "native_name": "Србија"},
    {"name": "Slovakia", "code": "SK", "native_name": "Slovensko"},
    {"name": "Slovenia", "code": "SI", "native_name": "Slovenija"},
    {"name": "Spain", "code": "ES", "native_name": "España"},
    {"name": "Sweden", "code": "SE", "native_name": "Sverige"},
    {"name": "Switzerland", "code": "CH", "native_name": "Schweiz"},
    {"name": "Ukraine", "code": "UA", "native_name": "Україна"},
    {
        "name": "United Arab Emirates",
        "code": "AE",
        "native_name": "الإمارات العربية المتحدة",
    },
    {"name": "United Kingdom", "code": "GB", "native_name": "United Kingdom"},
    {"name": "United States", "code": "US", "native_name": "United States"},
    {"name": "Vatican City", "code": "VA", "native_name": "Città del Vaticano"},
]
