# Generated by Django 4.2 on 2024-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business_user",
            field=models.BooleanField(
                default=False,
                help_text="Is the user related to a business customer. A company\n        registered as a customer may have many users.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_company_admin",
            field=models.BooleanField(
                default=False,
                help_text="Every company registerd as a business customer requires\n        an admin. Only the company admin can add users to the company.",
            ),
        ),
    ]
