# Generated by Django 5.2.4 on 2025-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_full_name_delete_userfavoriteproperty"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="agreed_to_terms",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user agreed to the terms of use.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Has the account been verified (e.g., KYC or email)?",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Optional contact number.",
                max_length=20,
                null=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile image.",
                null=True,
                upload_to="profiles/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe customer ID used for payments.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                help_text="Indicates current subscription status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Required. Used as the login identifier.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="User’s given name.",
                max_length=150,
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated full name from first and last name.",
                max_length=301,
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_business_user",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if user is part of a business customer account. Businesses can add multiple users.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_company_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is an admin of the company. Admins manage users and settings.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="User’s family name.",
                max_length=150,
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional public username. Not used for login. Must be unique if set.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
